language: node_js

node_js:
- node

script: npm run build

deploy:
  provider: azure_web_apps
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master
  repo: robgallen/robgallen.github.io
  target-branch: master
